Partial Crime Data Methods Added
ASE-ESRS/MARTIN-client pull request #33
Opened 2017-12-11 15:45 UTC by LoicVerrall

2017-12-12 11:11 UTC, msp26ssx reviewed
All looks good as per the API guide, only thing is the get() methods of CrimeClusterItem() currently return null-is this intentional?

2017-12-12 11:25 UTC, msp26ssx reviewed
Also, might be worth checking for a 503 response and submitting a new request with a smaller boundary area if this is the case?

2017-12-12 12:50 UTC, danarth requested changes

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/Permissions.java
> +    int INTERNET_PERMISSION = 2;
Why have you removed `public static final` from these permissions?

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/activities/MainActivity.java
> +        mapFragment.mainActivity = this;
There is no need for this. Whenever you need to access `MainActivity` from `MapFragment` just simply use `getActivity()` from inside the fragment.

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
> +    public MainActivity mainActivity;
See my comment on L53 of `MainActivity.java`.

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
> +                mClusterManager = new ClusterManager<CrimeClusterItem>(mainActivity, mGoogleMap);
Instead of `mainActivity` use `getActivity()`

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
> +                    double longitude = Double.parseDouble(obj.getJSONObject("location").getString("longitude"));
Instead of `Double.parse` you can use:

````java
obj.getJSONObject("location").getDouble("latitude");
````

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
>                  }
After L367 please add the following line:
````java
mGoogleMap.setOnCameraIdleListener(mClusterManager);
````
Otherwise the clusters do not show.

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/util/CrimeClusterItem.java
> +        return null;
If these methods are not implemented then the app throws a `NullPointerException` upon loading. Please implement this method as follows:
````java
@Override
public LatLng getPosition() {
    return mPosition;
}
````

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/util/CrimeClusterItem.java
> +        return null;
You must also implement this method or else we get a `NullPointerException` upon loading the code.

````java
@Override
public String getTitle() {
    return mTitle;
}
````

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/util/CrimeClusterItem.java
> +        return null;
This method is not implemented in our app but you should return the empty string `""` instead of `null`.

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/util/DefaultsManager.java
> -}
Is there a reason we've deleted this class? I thought we were using it to set defaults upon initial launch?

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/util/JSONArrayUtils.java
> +    static int getAveragePrice(JSONArray array) throws JSONException {
Is there a reason you've removed the `public` keyword from all of these method signatures?

2017-12-12 12:50 UTC, DanielArthurUK commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
> +                mClusterManager = new ClusterManager<CrimeClusterItem>(mainActivity, mGoogleMap);
This `ClusterManager` should be instantiated in the `onMapReadyCallback` method just after the `mGoogleMap` object is defined.

2017-12-12 12:51 UTC, DanielArthurUK commented
@LoicVerrall I am going to close this pull request until your changes are implemented to avoid accidental merging. When you have made the changes re-open the PR and I will look at it alongside @msp26ssx

2017-12-12 15:35 UTC, LoicVerrall commented on app/src/main/java/ase_esrs/martinsmap/ui/fragments/MapFragment.java
> +                mClusterManager = new ClusterManager<CrimeClusterItem>(mainActivity, mGoogleMap);
I'm not doing this, okay? First are foremost, it is desirable to have the cluster manager reinitialised whenever the map configuration (e.g. search radius) is changed. Secondly, you're fat

2017-12-13 03:14 UTC, DanielArthurUK commented
@LoicVerrall Your recent changes failed the [Travis build](https://travis-ci.org/ASE-ESRS/MARTIN-client/builds/315637417?utm_source=github_status&utm_medium=notification). I think it's because of the package structure reshuffling.

Travis complains about not being able to find the package `util` in the `CrimeClusterItem` class. Some of your code might therefore need changing.

2017-12-13 11:07 UTC, DanielArthurUK commented
@LoicVerrall are you happy for me to merge this now?

2017-12-13 11:18 UTC, danarth approved these changes

2017-12-13 11:43 UTC, merged